# ----
# Site

title: Brendan McCaffrey
url: "https://brendanmccaffrey.com"
baseurl: 
google_analytics_key:
google_maps_javascript_api_key: AIzaSyDcGWwimVaVzYbPBH3MJOAg6ZvjpRHSWn4
disqus_shortname: brendanmccaffrey

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: 
author:
  name: Brendan McCaffrey
  email: brendanmccaffrey17@gmail.com
  Instagram: brendanmccaffrey17 # instagram username 
social:
  name: Brendan McCaffrey
  links:
    - https://github.com/brendan-mccaffrey

# -----
# Build

timezone: Etc/UTC

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  staff_members:
    _hide_content: true

paginate: 10
paginate_path: "/blog/:num/"

jekyll-archives:
  enabled: ['categories']

defaults:
  -
    scope:
      path: "/_files/"
    values:
      permalink: /file.pdf
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      _options:
        image:
          width: 2000
          height: 1322
          resize_style: cover
        content:
          width: 1500
          height: 2000
  -
    scope:
      path: "contact-success.html"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "pages"
    values:
      image:
        width: 2000
        height: 1322
        resize_style: cover
      bottom_image:
        width: 2000
        height: 1322
        resize_style: cover

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Github
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Email
  - RSS

_comments:
  description: The online destination for Brendan McCaffrey
  blurb: kinda a don
